# Caso práctico 3 - Medidas de ahorro energético
En esta última parte del caso práctico vamos a calcular algunas medidas de ahorro energético.
MAES propuestas
1. Cambio de alumbrado a LED.
2. Optimización recargo energía reactiva.
3. Placas fotovoltaicas para autoconsumo.
4. Bombas hidráulicas eficientes.
En la explicación de cada mejora encontrareis las preguntas a responder en el cuestionario.

Nota: Utilizad los mismos datos iníciales que en el capítulo 6.
* 5% anual la energía eléctrica
* 3% anual el gas natural.
* Tasa 10% para el VAN i el TIR
* VAN/TIR a 5 años.
* Precio energía eléctrica: 0,16€/kWh

-------------------------------

Cuestionario de autoevaluación del caso práctico - parte 3
# Pregunta 1

MAE1 - Cambio de luminarias (I)

¿Cuál será el ahorro energético total debido a los dos cambios (fluorescentes y downlights)? (kWh/año).

Nota 1: Downlight: el consumo de 24W es para toda la luminaria LED. Fluorescentes: el consumo de 24W es para una sola lámpara. Una luminaria de 2 lámparas consumirá el doble.

Nota 2: Tened en cuenta el consumo del balastro para calcular el consumo energético actual.

Respuesta:

In [ ]:
# p1

In [23]:
# /respuesta pregunta 1//////////////////////
#  definir en las tablas las variables
import numpy as np
import pandas as pd
import datetime

pd.options.mode.chained_assignment = None  # default='warn'
import matplotlib.pyplot as plt
import base64
from io import BytesIO


# ls datos/efe*.*

df=pd.read_csv("datos/iluminacion.csv", header=0)

df=df.drop(columns=['Balastro'])
# 
df['Pot_ud']=df.Potencia
conbalastro = {
18: 24,
26: 32, 
58: 64
}
df=df.replace({'Pot_ud':conbalastro})
# 

potu={
'Donlight': 24/2,
'Fluorescentes':24
}

df['Wled']=df.Tipo
df=df.replace({'Wled':potu})


df['kwh0']=df.udp*df.Unidades*df.Pot_ud*df.horas_ano/1000
df['kwh1']=df.udp*df.Unidades*df.Wled*df.horas_ano/1000

df['euros0']=df.kwh0*0.16
df['euros1']=df.kwh1*0.16





de=df.sum().kwh0-df.sum().kwh1
df
de

7880.0

# Pregunta 2

MAE1 - Cambio luminarias (II)

Al proponer el cambio de tecnología actual a LED alargamos el número de horas que durarán las lámparas, por lo que el numero de reemplazos de estas sera menos en el tiempo.

¿Supondrá un ahorro económico en los dos casos, downlights y fluorescentes? 

Nota 1: El coste del cambio de las lámparas actuales son de 9€ para cada lámpara (18€ por luminaria de 2x26W) de 26W y 12€ por la de 58W (24€ por luminaria de 2x58W).

 
Seleccione una:
* a. Supone un ahorro económico para los dos casos.
* b. Solo supone ahorro económico para los downlights.
* c. Solo supone ahorro económico para los fluorescentes.
* d. No supone ahorro económico en ningún caso.

In [24]:
# p2-a  no hecho, estimado
coste_reemplazo={
'Donlight': 24/2,
'Fluorescentes':24
}


df['Wled']=df.Tipo
df=df.replace({'Wled':potu})


df['kwh0']=df.udp*df.Unidades*df.Pot_ud*df.horas_ano/1000
df['kwh1']=df.udp*df.Unidades*df.Wled*df.horas_ano/1000

df['euros0']=df.kwh0*0.16
df['euros1']=df.kwh1*0.16

df

,Planta,Local,Tipo,udp,Potencia,Unidades,Área,Em,horas_ano,Pot_ud,Wled,kwh0,kwh1,euros0,euros1
0,baja,Vestíbulo,Donlight,2,26,5,33,151,2500,32,12.0,800.0,300.0,128.00,48.00
1,baja,Sala Informática,Donlight,2,26,6,19,411,2000,32,12.0,768.0,288.0,122.88,46.08
2,baja,Sala polivalente,Fluorescentes,2,58,13,285,320,2000,64,24.0,3328.0,1248.0,532.48,199.68
3,baja,Sala Ensayo,Fluorescentes,2,58,2,10,380,1500,64,24.0,384.0,144.0,61.44,23.04
4,sotano,Aula 1,Fluorescentes,2,58,5,100,301,1500,64,24.0,960.0,360.0,153.60,57.60
5,sotano,Aula 2,Fluorescentes,2,58,2,32,270,1500,64,24.0,384.0,144.0,61.44,23.04
6,sotano,Aula 3,Fluorescentes,2,58,2,33,264,1500,64,24.0,384.0,144.0,61.44,23.04
7,sotano,Aula 4,Fluorescentes,2,58,4,71,299,1500,64,24.0,768.0,288.0,122.88,46.08
8,sotano,Rocódromo,Fluorescentes,2,58,2,55,144,1500,64,24.0,384.0,144.0,61.44,23.04
9,sotano,Pasadizo,Fluorescentes,2,58,2,50,175,2500,64,24.0,640.0,240.0,102.40,38.40
10,primera,Sala reuniones,Donlight,2,26,4,18,501,1000,32,12.0,256.0,96.0,40.96,15.36
11,primera,Despacho,Donlight,2,26,4,17,350,2500,32,12.0,640.0,240.0,102.40,38.40
12,primera,Sala Formación 1,Donlight,2,26,4,20,280,1500,32,12.0,384.0,144.0,61.44,23.04
13,primera,Sala Formación 2,Fluorescentes,2,58,4,49,346,1500,64,24.0,768.0,288.0,122.88,46.08
14,Bar,Bar,Donlight,2,26,11,51,225,2500,32,12.0,1760.0,660.0,281.60,105.60


# Pregunta 3

MAE1 - Cambio luminarias (III)

¿Qué opción de las dos es más viable según el VAN de cada una?

Seleccione una:
* a. Downlights
* b. Fluorescentes

In [ ]:
# p3-a no hecho cogidos valores de p221

# Pregunta 4

MAE2 - Energia reactiva (I)

Según los datos del ejercicio la potencia mínima a compensar por la batería de condensadores es de Respuesta
  KvAr y según la base CYPE tiene un coste de Respuesta
€

Nota: Las baterías de condensadores están el capítulo IE de la base de datos. Usad la marca genérica y el modelo de potencia inmediata superior (http://www.generadordeprecios.info/)

In [ ]:
# p4

In [ ]:
#  parte 1 Pregunta 6 ¿Existió recargo por energía reactiva en 2010? ¿En caso afirmativo que sobrecoste tuvo?

# mal a mi me daba 459.17 por haber usado 1/3 en lugar de 0.33
# Repasad el apartado 2.2.1 el capítulo de recargo de reactiva, página 87 del capítulo 2.
# La respuesta correcta es: 464

from numpy import *
import pandas as pd
import datetime

pd.options.mode.chained_assignment = None  # default='warn'
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib import pyplot
import base64
from io import BytesIO

# ====================================================
# ====================================================


dfa=pd.read_csv("datos/e_kwh.csv", header=[0])

dfa=dfa.loc[dfa.ano==2010]
dfa=dfa.set_index('mes')
dfa=dfa.drop(['ano'], axis=1)
dfa['P1']=dfa.p1+dfa.p4
dfa['P2']=dfa.p2+dfa.p5

dfr=pd.read_csv("datos/kvar.csv", header=[0])
dfr=dfr.loc[dfr.ano==2010]
dfr=dfr.set_index('mes')
dfr=dfr.drop(['ano'], axis=1)
dfr['P1']=dfr.p1+dfr.p4
dfr['P2']=dfr.p2+dfr.p5
# 
dfr=dfr.astype(float)
dfa=dfa.astype(float)
# 
df=pd.DataFrame()
df['mes']=dfr.index
df=df.set_index('mes')

df['e1']=where(dfr.P1-dfa.P1/3 < 0,0,dfr.P1-dfa.P1*0.33 )
df['e2']=where(dfr.P2-dfa.P2/3 < 0,0,dfr.P2-dfa.P2*0.33  )

# 

df['cfi1']=cos(arctan(dfr.P1/dfa.P1))
df['cfi2']=cos(arctan(dfr.P2/dfa.P2))

# 
df['rec1']= where(df.cfi1 >= 0.95,0,where(df.cfi1 <= 0.80,0.062332 ,0.041554 ))
df['rec2']= where(df.cfi2 >= 0.95,0,where(df.cfi2 <= 0.80,0.062332 ,0.041554 ))
# 
df['rect1']=df.e1*df.rec1
df['rect2']=df.e2*df.rec2
# 
recargo_total=df.sum().rect1+df.sum().rect2
recargo_total
# df

In [ ]:
df

In [ ]:
# en la tabla 
pmax=43
tabla=0.447
kvar=pmax*tabla
kvar

# Pregunta 5

MAE2 - Energia reactiva (II)

¿Cuál es el VAN de la instalación de bateria de condensadores?

Nota : no suponer aumento anual del precio de la energía eléctrica.

Respuesta:

In [ ]:
# p5

In [ ]:
# import
import warnings
warnings.filterwarnings('ignore')
# 
import numpy as np
import pandas as pd
import datetime

pd.options.mode.chained_assignment = None  # default='warn'
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib import pyplot
import base64
from io import BytesIO

# ====================================================
# ====================================================

In [ ]:
# periodo de retorno
inversion=1500
inv=1065.69
aa=464.79
pp=inv/aa
pp

In [ ]:
Inversion=inv
ahorro=aa
# Inversion=1500
# ahorro=624

# VAN

ii=0.00 # incremento anual del precio de la electricidad
xx=[]
yy=[]
for x in range(1,6):
    xx.append(x)
    yy.append(ceil(ahorro*(1+ii)**x-1))
cashFlows=[-Inversion]
# cashFlows.extend([ahorro])
cashFlows.extend(yy)
# 
k=10
npv = round(np.npv(k/100, cashFlows),1);  
irr = round(np.irr(cashFlows)*100,1);    
# 


# solo para presentar los datos

rr4=pd.DataFrame()
rr4['Tasa k (%)']= [k]
rr4['Inversion']=[-Inversion]
rr4[xx]=yy
rr4['VAN']=npv
rr4['TIR']=irr


rr4=rr4.T
rr4

# Pregunta 6

MAE3 - Fotovoltaica (I)

¿Cuanta energía de más puede producir anualmente la planta de 6Kwp respecto la de 3kWp?

Nota: para el cálculo del PVGIS utilizad la base SARAH 14% de pérdidas y ángulo 0º y inclinación 38º

https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html#PVP

Respuesta:

In [ ]:
# p6

In [ ]:
# p10- d
# S O L U C I O N
# ==================================================
# importS
import warnings
warnings.filterwarnings('ignore')
# 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import requests as requests
import json
# ==================================================
pd.options.mode.chained_assignment = None  # default='warn'
import matplotlib.pyplot as plt
import base64
from io import BytesIO
# ==================================================

# https://ec.europa.eu/jrc/en/PVGIS/docs/noninteractive
# # madrid
# lat=40.436
# lon=-3.686
#gerona
lat=41.987361
lon=2.826335

angle=38
aspect=0
# potencia pico instalada
n=50
loss=14
ddff=pd.DataFrame()
# ==================================================
wp=3000/n # por panel
peakpower=n*wp/1000 # kwp

peakpowers=[6,3]
for peakpower in peakpowers:
    tt="&peakpower="+str(peakpower)+"&lat="+str(lat)+"&lon="+str(lon)+"&angle="+str(angle)+"&aspect="+str(aspect)+"&&loss="+str(loss)+"&global="+str(1)
    r = requests.get("https://re.jrc.ec.europa.eu/api/PVcalc?"+tt+"&outputformat=json")
    df=pd.read_json(json.dumps(r.json()["outputs"]["monthly"]["fixed"], indent=2), orient='records') 
    ddff['kWp_'+str(peakpower)]=df['E_m']
# ==================================================
ddff.index=df['month']
ax=ddff.plot(kind='bar',title=tt,figsize=(15,5));
img = BytesIO();plt.savefig(img, format='png')
ff2 = ('<img src="data:image/png;base64,{}">'.format(base64.b64encode(img.getvalue()).decode()))
# plt.close()
ddffT=ddff.T

ddffT['Total']=(ddff.sum(axis=0).tolist())
ddffa=ddffT.T
ddffa.T.diff()

# ==================================================

# Pregunta 7

MAE3 - Fotovoltaica (II)

¿Cuánta energía aprovechamos en cada caso?

Nota: Para la planta de 3Kwp se aprovecha el 100% de la producción solar ya que siempre consumimos esta potencia. Para la de 6kW podéis suponer que se aprovecha un 80% en periodo de horario estival (abril-octubre) y un 40% en período de horario invernal (noviembre a marzo).

Seleccione una:
* a. 3kwp = 4.570 kWh
* 6 kWp = 9.141 kWh
* b. 3kwp = 5.897 kWh
* 6 kWp = 4.570 kWh
* c. 3 kwp = 4.570 kWh
* 6 kWp = 5.987  kWh
* d. El doble en la de 6kWp respecto la de 3kWp.

In [ ]:
# p7

In [ ]:
# p10- d
# S O L U C I O N
# ==================================================
# importS
import warnings
warnings.filterwarnings('ignore')
# 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import requests as requests
import json
# ==================================================
pd.options.mode.chained_assignment = None  # default='warn'
import matplotlib.pyplot as plt
import base64
from io import BytesIO
# ==================================================

# https://ec.europa.eu/jrc/en/PVGIS/docs/noninteractive
# # madrid
# lat=40.436
# lon=-3.686
#gerona
lat=41.987361
lon=2.826335

angle=38
aspect=0
# potencia pico instalada
n=50
loss=14
ddff=pd.DataFrame()
# ==================================================
wp=3000/n # por panel
peakpower=n*wp/1000 # kwp

peakpowers=[6,3]
for peakpower in peakpowers:
    tt="&peakpower="+str(peakpower)+"&lat="+str(lat)+"&lon="+str(lon)+"&angle="+str(angle)+"&aspect="+str(aspect)+"&&loss="+str(loss)+"&global="+str(1)
    r = requests.get("https://re.jrc.ec.europa.eu/api/PVcalc?"+tt+"&outputformat=json")
    df=pd.read_json(json.dumps(r.json()["outputs"]["monthly"]["fixed"], indent=2), orient='records') 
    ddff['kWp_'+str(peakpower)]=df['E_m']
# ==================================================
ddff.index=df['month']




ax=ddff.plot(kind='bar',title=tt,figsize=(15,5));
img = BytesIO();plt.savefig(img, format='png')
ff2 = ('<img src="data:image/png;base64,{}">'.format(base64.b64encode(img.getvalue()).decode()))
# plt.close()
ddffT=ddff.T

ddffT['Total']=(ddff.sum(axis=0).tolist())
ddffa=ddffT.T
ddffa.T.diff()

aa=ddff.copy()
aa['verano']=aa.index.isin([4,5,6,7,8,9])
aa.loc[aa['verano'] == True, 'a6'] = 0.8
aa.loc[aa['verano'] == False, 'a6'] = 0.4
aa.loc[aa['verano'] == True, 'a3'] = 1
aa.loc[aa['verano'] == False, 'a3'] = 1
aa['ea6']=aa.kWp_6*aa.a6
aa['ea3']=aa.kWp_3*aa.a3
print(aa.sum().ea3,aa.sum().ea6)

# Pregunta 8

MAE3 - Fotovoltaica (III)¿

 ¿En función del TIR de cada opción cual recomendaríais?

Nota: En este caso usad el TIR a 10 años.

Seleccione una:
* a. Planta 3kWp
* b. Planta de 6kWp

In [ ]:
# p8

In [ ]:
# S O L U C I O N
# ==================================================
# importS
import warnings
warnings.filterwarnings('ignore')
# 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import requests as requests
import json
# ==================================================
pd.options.mode.chained_assignment = None  # default='warn'
import matplotlib.pyplot as plt
import base64
from io import BytesIO
# ==================================================

# https://ec.europa.eu/jrc/en/PVGIS/docs/noninteractive
# # madrid
# lat=40.436
# lon=-3.686
#gerona
lat=41.987361
lon=2.826335

angle=38
aspect=0
# potencia pico instalada
n=50
loss=14
ddff=pd.DataFrame()
# ==================================================
wp=3000/n # por panel
peakpower=n*wp/1000 # kwp

peakpowers=[6,3]
for peakpower in peakpowers:
    tt="&peakpower="+str(peakpower)+"&lat="+str(lat)+"&lon="+str(lon)+"&angle="+str(angle)+"&aspect="+str(aspect)+"&&loss="+str(loss)+"&global="+str(1)
    r = requests.get("https://re.jrc.ec.europa.eu/api/PVcalc?"+tt+"&outputformat=json")
    df=pd.read_json(json.dumps(r.json()["outputs"]["monthly"]["fixed"], indent=2), orient='records') 
    ddff['kWp_'+str(peakpower)]=df['E_m']
# ==================================================
ddff.index=df['month']

In [ ]:
ax=ddff.plot(kind='bar',title=tt,figsize=(15,5));
img = BytesIO();plt.savefig(img, format='png')
ff2 = ('<img src="data:image/png;base64,{}">'.format(base64.b64encode(img.getvalue()).decode()))
plt.close()
ddffT=ddff.T

ddffT['Total']=(ddff.sum(axis=0).tolist())
ddffa=ddffT.T
ddffa.T.diff()

aa=ddff.copy()
aa['verano']=aa.index.isin([4,5,6,7,8,9])
aa.loc[aa['verano'] == True, 'a6'] = 0.8
aa.loc[aa['verano'] == False, 'a6'] = 0.4
aa.loc[aa['verano'] == True, 'a3'] = 1
aa.loc[aa['verano'] == False, 'a3'] = 1
aa['ea6']=aa.kWp_6*aa.a6
aa['ea3']=aa.kWp_3*aa.a3

Precio_electricidad_medio=0.16#€/kWh

aa['eea6']=aa['ea6']*Precio_electricidad_medio
aa['eea3']=aa['ea3']*Precio_electricidad_medio

ahorros=[aa.sum().eea6,aa.sum().eea3]

# print(aa.sum().eea3,aa.sum().eea6)

In [ ]:
# periodo de retorno
Inversions=peakpowers

# Inversion=1500
# ahorro=624
Inversion,ahorros

In [ ]:
# VAN
Inversion=Inversions[1]*1000
ahorro=ahorros[1]
# Inversion=Inversions[0]*1000
# ahorro=ahorros[0]
ii=0.00 # incremento anual del precio de la electricidad
xx=[]
yy=[]
for x in range(1,11):
    xx.append(x)
    yy.append(np.ceil(ahorro*(1+ii)**x-1))
cashFlows=[-Inversion]
# cashFlows.extend([ahorro])
cashFlows.extend(yy)
# 
k=10
npv = round(np.npv(k/100, cashFlows),1);  
irr = round(np.irr(cashFlows)*100,1);    
# 


# solo para presentar los datos

rr4=pd.DataFrame()
rr4['Tasa k (%)']= [k]
rr4['Inversion']=[-Inversion]
rr4[xx]=yy
rr4['VAN']=npv
rr4['TIR']=irr


rr4=rr4.T
rr4

# Pregunta 9

MAE4 - Bombas eficientes

¿Cuál sería el período de retorno (años) del sobrecoste de la inversión para las bombas eff1 respecto las eff3? 

Nota: todas las bombas son monofásicas

 

Respuesta:

In [ ]:
# p9

In [45]:
# pag 257
# tema3
# error eff1 por ffe3
# tablillas
# motores cambiarlos por otros de mayor rendimiento
# es la potencia en el eje / rnedimiento
# numero de motores y numero de horas = kwh ano
# inversion de cambio motores por modelo * 0.11 euros kw como hemos puesto 3 anos, amortizacion simple de 3anos
# rr=pd.read_csv("datos/motor.csv", index_col=0, header=[0,1])

ee=pd.DataFrame()

# para los valores intermedios obtenidos para,

# n, Numero de motores
# p, Potencia, en W
# d, Dias al ano funcionando
# h, Horas al dia funcionando
# c, carga

mmc=['n','p','d','h']
mm=[
[1,545,220,8],
[1,240,365,10],
]

# mm
ee=pd.DataFrame(mm)
ee.columns=mmc
ee['e0']=ee.p*ee.d*ee.h/1000*0.16
ee['e3']=ee.e0*70/76.2
ee['e1']=ee.e0*70/82.8

2500/ee.sum().e1-1800/ee.sum().e3

# ee['inv']=[1800,2500]



# ee['tr3']=ee.inv/ee.e3



# ee.at[3,'p']=22 # la potencia de 25 no esta enla tabla

# # dd=rr.IE1['8-poles'][p].tolist()
# # ee
# ee['r1']=rr.IE1['6-poles'][ee.p.tolist()].tolist()
# ee['r3']=rr.IE3['6-poles'][ee.p.tolist()].tolist()
# ee.at[3,'p']=25
# ee['kw1']=ee.p/ee.r1*100
# ee['kw3']=ee.p/ee.r3*100
# # retorno sea en 3 anos
# ee['Inv']=(ee.kw1-ee.kw3)*ee.d*ee.h*ee.n*0.11*3
# aae=round(((ee.kw1-ee.kw3)*ee.d*ee.h*ee.n*0.11).sum(),1)

# # ahorro emisiones
# ee['dCO2']=(ee.kw1-ee.kw3)*ee.d*ee.h*ee.n*0.385




# aa=round(ee.copy(),1)
# aa=aa[['Inv','dCO2']]
# aa.loc['total']=aa.sum()
# ii=aa.at['total','Inv']
# aaco2=aa.at['total','dCO2']
# # ee



# r1, rendimineto si clase IE1
# r3, rendimineto si clase IE3
# kw1, consumo si clase IE1, en kW
# kw3, consumo si clase IE3, en kW

# ee

3.397839083322954

In [36]:
ii=100000
aa=10000
pr=ii / aa

rr1=pd.DataFrame(index=['uds','Fotovoltaica'])
rr1['Inversion']=['€',ii]
rr1['Ahorro']=['€',aa]                 
rr1['Periodo_de_retorno']=['años',pr] 
rr1

             Inversion Ahorro Periodo_de_retorno
uds                  €      €               años
Fotovoltaica    100000  10000                 10

# Pregunta 10

MAE4 - Bombas eficientes

¿Cuál seria el VAN de la inversión de las bombas eff1 respecto las actuales?

Seleccione una:
* a. Negativo
* b. 866,42
* c. 1,7
* d. 3249,0

In [46]:
Inversion=2500
ahorro=ee.sum().e1

In [49]:
Periodo=[1,2,3,4,5]
ii=0.0
xx=[]
for x in Periodo[:9]:
    xx.append(ahorro*(1+ii)**x-1)
cashFlows=[-Inversion]
cashFlows.extend([ahorro])
cashFlows.extend(xx)
# 
k=0.1
npv = round(np.npv(k, cashFlows),1); 
npv

<ipython-input-49-9054385e09c4>:11: DeprecationWarning: numpy.npv is deprecated and will be removed from NumPy 1.20. Use numpy_financial.npv instead (https://pypi.org/project/numpy-financial/).
  npv = round(np.npv(k, cashFlows),1);

-1422.3

## solucion

Pregunta 1
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
MAE1 - Cambio de luminarias (I)

¿Cuál será el ahorro energético total debido a los dos cambios (fluorescentes y downlights)? (kWh/año).

Nota 1: Downlight: el consumo de 24W es para toda la luminaria LED. Fluorescentes: el consumo de 24W es para una sola lámpara. Una luminaria de 2 lámparas consumirá el doble.

Nota 2: Tened en cuenta el consumo del balastro para calcular el consumo energético actual.

Respuesta:
7880
Correcta
Retroalimentación
La respuesta correcta es: 7880
Pregunta 2
Incorrecta
Puntúa 0,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
MAE1 - Cambio luminarias (II)

Al proponer el cambio de tecnología actual a LED alargamos el número de horas que durarán las lámparas, por lo que el numero de reemplazos de estas sera menos en el tiempo.

¿Supondrá un ahorro económico en los dos casos, downlights y fluorescentes? 

Nota 1: El coste del cambio de las lámparas actuales son de 9€ para cada lámpara (18€ por luminaria de 2x26W) de 26W y 12€ por la de 58W (24€ por luminaria de 2x58W).

 

 

Seleccione una:
a. Supone un ahorro económico para los dos casos.
b. Solo supone ahorro económico para los downlights. Incorrecta
c. Solo supone ahorro económico para los fluorescentes.
d. No supone ahorro económico en ningún caso.
Retroalimentación
La respuesta correcta es: Supone un ahorro económico para los dos casos.
Pregunta 3
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
MAE1 - Cambio luminarias (III)

¿Qué opción de las dos es más viable según el VAN de cada una?

Seleccione una:
a. Downlights Correcta
b. Fluorescentes
Retroalimentación
La respuesta correcta es: Downlights
Pregunta 4
Incorrecta
Puntúa 0,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
MAE2 - Energia reactiva (I)

Según los datos del ejercicio la potencia mínima a compensar por la batería de condensadores es de Respuesta
19,2
Incorrecta

  KvAr y según la base CYPE tiene un coste de Respuesta
1065,7
Incorrecta

€

Nota: Las baterías de condensadores están el capítulo IE de la base de datos. Usad la marca genérica y el modelo de potencia inmediata superior (http://www.generadordeprecios.info/)

 

 

Pregunta 5
Incorrecta
Puntúa 0,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
MAE2 - Energia reactiva (II)

¿Cuál es el VAN de la instalación de bateria de condensadores?

Nota : no suponer aumento anual del precio de la energía eléctrica.

Respuesta:
693,2
Incorrecta
Retroalimentación
La respuesta correcta es: 771
Pregunta 6
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
MAE3 - Fotovoltaica (I)

¿Cuanta energía de más puede producir anualmente la planta de 6Kwp respecto la de 3kWp?

Nota: para el cálculo del PVGIS utilizad la base SARAH 14% de pérdidas y ángulo 0º y inclinación 38º

https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html#PVP

Respuesta:
4564,8
Correcta
Retroalimentación
La respuesta correcta es: 4570
Pregunta 7
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
MAE3 - Fotovoltaica (II)

¿Cuánta energía aprovechamos en cada caso?

Nota: Para la planta de 3Kwp se aprovecha el 100% de la producción solar ya que siempre consumimos esta potencia. Para la de 6kW podéis suponer que se aprovecha un 80% en periodo de horario estival (abril-octubre) y un 40% en período de horario invernal (noviembre a marzo).

Seleccione una:
a. 3kwp = 4.570 kWh
6 kWp = 9.141 kWh
b. 3kwp = 5.897 kWh
6 kWp = 4.570 kWh
c. 3 kwp = 4.570 kWh
6 kWp = 5.987  kWh Correcta
d. El doble en la de 6kWp respecto la de 3kWp.
Retroalimentación
La respuesta correcta es: 3 kwp = 4.570 kWh
6 kWp = 5.987  kWh
Pregunta 8
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
MAE3 - Fotovoltaica (III)¿

 ¿En función del TIR de cada opción cual recomendaríais?

Nota: En este caso usad el TIR a 10 años.

Seleccione una:
a. Planta 3kWp Correcta
b. Planta de 6kWp
Retroalimentación
La respuesta correcta es: Planta 3kWp
Pregunta 9
Incorrecta
Puntúa 0,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
MAE4 - Bombas eficientes

¿Cuál sería el período de retorno (años) del sobrecoste de la inversión para las bombas eff1 respecto las eff3? 

Nota: todas las bombas son monofásicas

 

Respuesta:
3,4
Incorrecta
Retroalimentación
La respuesta correcta es: 18
Pregunta 10
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
MAE4 - Bombas eficientes

¿Cuál seria el VAN de la inversión de las bombas eff1 respecto las actuales?

Seleccione una:
a. Negativo Correcta
b. 866,42
c. 1,7
d. 3249,0
Retroalimentación
La respuesta correcta es: Negativo