In [1]:
# ///////////////////////////////////////////////
#  definir en las tablas las variables
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import datetime

pd.options.mode.chained_assignment = None  # default='warn'
import matplotlib.pyplot as plt
import base64
from io import BytesIO


# ls datos/efe*.*
df=pd.DataFrame()

Cuestionario de autoevaluación del capítulo 5
# Pregunta 1

Una empresa de servicios energéticos es aquella empresa que...

Seleccione una:
* a. Genera energía eléctrica
* b. Invierte en eficiencia energética y recupera parte de  inversión de los ahorros.
* c. Es un banco.
* d. Ninguna de las anteriores.

In [2]:
# p1- b

# Pregunta 2

En la descripción técnica de una MAES encontraremos:

Seleccione una o más de una:
* a. Los kWh ahorrados.
* b. La ficha técnica de los equipos consumidores de energía que contiene la mejora.
* c. La inversión de la MAE
* d. El VAN de la inversión.
* e. Emplazamiento de la mejora

In [3]:
# p2- b,c,e

# Pregunta 3

¿Qué inversión supone una caldera de biomasa de pellets generica de 60kW?

Accesorios para el sistema de mando: Ninguno.

Alimentación: Déposito con sistema de aspiración.

Accesorios: todos excepto presostato.

 

Nota: usar la base de precios de CYPE

Seleccione una:
* a. 17.326€
* b. 11.220€
* c. 18.560€
* d. 12.000€

In [4]:
# p3-  !!! no carga cype

#  ejemplo p207 apuntes
# http://www.generadordeprecios.info/rehabilitacion/Instalaciones/Iluminacion/Interior/Luminaria_empotrada_tipo_Downlight.html#gsc.tab=0

# http://www.generadordeprecios.info/rehabilitacion/Instalaciones/IC_Calefaccion__climatizacion_y_A/Calderas_de_biomasa/Caldera_para_la_combustion_de_pellets.html#gsc.tab=0

# Pregunta 4

Tenemos la siguiente propuesta de MAEs

Inversión: 22.000€

Ahorro anual: 8.250€

¿Cuál sería el período de retorno de la inversión?

Seleccione una:
* a. 2,66
* b. 0,37

In [5]:
# p4- a

Inversion=22000
Ahorro =8250
PR = Inversion / Ahorro 
PR

2.6666666666666665

In [6]:
# apuntes p212

# ejemplo calculo pr de una maes


# valor del dinero
# futuro
va=50000
i=0.03
n=5
fvf=va*(1+i)**n

# presente
vf=50000
n=5
i=0.03


pva=vf/(1+i)**n


Inversion=143000
Ahorro =12820
PR = Inversion / Ahorro 
PR

fvf,pva,PR

(57963.703715, 43130.439219208194, 11.154446177847113)

# Pregunta 5
En la MAE anterior tenemos 8.250€ de ahorro anuales. Estos ahorros de 8.250€ generados dentro de 5 años que valor económico tendrían a día de hoy con una tasa del 10%.

Seleccione una:
* a. 5.123
* b. 8.250€
* c. 13.286€
* d. El valor económico es siempre el mismo al largo del tiempo.

In [7]:
# p5- a
vf=8250
vf=8250
n=5
i=0.1


pva=vf/(1+i)**n
pva

5122.600915238028

# Pregunta 6

Siguiendo con el ejemplo anterior sabemos que los ahorros duraran 5 años. Calculad el VAN con una tasa de actualización del 10%.

Seleccione una:
* a. 19.250
* b. 8.250
* c. 9.274
* d. 31.274

In [8]:
# p6- c
inv=22000
k=0.1
df['ahorro']=[8250,8250,8250,8250,8250]
df['tt']=[1,2,3,4,5]
df['va']=df.ahorro/(1+k)**df.tt
# van
van=-inv+df.sum().va
van

9273.99084761969

In [9]:
# p214
inv=12250
k=0.1
df['ahorro']=[3100,3100,3100,3100,3100,]
df['tt']=[1,2,3,4,5]
df['va']=df.ahorro/(1+k)**df.tt
# van
van=-inv+df.sum().va
# van

# Pregunta 7

¿Qué valor tiene el TIR de la MAE anterior?

Seleccione una:
* a. Faltan datos.
* b. Negativo
* c. 9%
* d. 25%

In [10]:
# p7- d
# van y tir
initialInvestment   = -22000; # Negative, since it results in an outflow of cash
ahorro=8250
cashFlows           = [initialInvestment, ahorro, ahorro,ahorro,ahorro,ahorro,];
discountRate    = 0.1; # Nine percent per annum
# VAN
# Net Present Value
npv = round(np.npv(discountRate, cashFlows),1);  
irr = round(np.irr(cashFlows)*100,1);
# 
print("Net present value of the investment:%3.2f"%npv);
print("Internal rate of return:%3.1f"%irr);

Net present value of the investment:9274.00
Internal rate of return:25.4

# Pregunta 8

De los 8.250€ de ahorro anuales un 60% provienen de la electricidad y un 40% del gas natural. ¿Si suponemos que el precio de la electricidad aumentara un 5% anual y el del gas natural un 3% anual, cuál será el nuevo VAN?

Nota: En el ahorro del primer año ya teneis que aplicar el aumento.

 

Seleccione una:
* a. 13.954€
* b. 13.178€
* c. 12.965€
* d. El VAN será el mismo que el apartado anterior.

In [25]:
# p8- b
inv=22000
df=pd.DataFrame()
k=0.05
ahorro=8250*0.6
df['cashFlows_e']=[
ahorro*(1+k)**1,
ahorro*(1+k)**2,
ahorro*(1+k)**3,
ahorro*(1+k)**4,
ahorro*(1+k)**5
]

k=0.03
ahorro=8250*0.4
df['cashFlows_g']=[
ahorro*(1+k)**1,
ahorro*(1+k)**2,
ahorro*(1+k)**3,
ahorro*(1+k)**4,
ahorro*(1+k)**5
]


df
df['cashFlows']=df.cashFlows_e+df.cashFlows_g
cashFlows=df.cashFlows.tolist()
x=[-inv]
x.extend(cashFlows)
cashFlows=x
cashFlows
df=pd.DataFrame()
df['va']=cashFlows
k=0.1

# 
npv = round(np.npv(k, cashFlows),1);  
irr = round(np.irr(cashFlows)*100,1);

df.at['VAN','va']=npv
df.at['TIR','va']=irr
# 


df = df.replace({np.nan:  ""})
df

               va
0   -22000.000000
1     8596.500000
2     8958.345000
3     9336.242850
4     9730.935011
5    10143.198180
VAN  13177.500000
TIR     30.700000

# Pregunta 9

Por último, si a los ahorros resultantes de la pregunta anterior les aplicamos un 35% de impuestos que VAN tendríamos.

Seleccione una:
* a. 865,4€
* b. Un VAN negativo.
* c. 15.124€
* d. 4.157€

In [33]:
# p9- a

inv=22000
df=pd.DataFrame()
k=0.05
ahorro=8250*0.6
df['cashFlows_e']=[
ahorro*(1+k)**1,
ahorro*(1+k)**2,
ahorro*(1+k)**3,
ahorro*(1+k)**4,
ahorro*(1+k)**5
]

k=0.03
ahorro=8250*0.4
df['cashFlows_g']=[
ahorro*(1+k)**1,
ahorro*(1+k)**2,
ahorro*(1+k)**3,
ahorro*(1+k)**4,
ahorro*(1+k)**5
]


df
df['cashFlows']=(df.cashFlows_e+df.cashFlows_g)*(1-0.35)
cashFlows=df.cashFlows.tolist()
x=[-inv]
x.extend(cashFlows)
cashFlows=x
cashFlows
df=pd.DataFrame()
df['va']=cashFlows
k=0.1


# 
npv = round(np.npv(k, cashFlows),1);  
irr = round(np.irr(cashFlows)*100,1);

df.at['VAN','va']=npv
df.at['TIR','va']=irr
# 


df = df.replace({np.nan:  ""})
df

               va
0   -22000.000000
1     5587.725000
2     5822.924250
3     6068.557853
4     6325.107757
5     6593.078817
VAN    865.400000
TIR     11.500000

    tt ahorro       va ahorroxi     vaxi
0    1   5500     5000     3740     3400
1    2   5500  4545.45     3740  3090.91
2    3   5500  4132.23     3740  2809.92
3    4   5500  3756.57     3740  2554.47
4    5   5500  3415.07     3740  2322.25
VAN            10849.3            4177.5
TIR                 47              25.3

# Pregunta 10

Para comparar dos inversiones de un cambio de luminarias utilizaremos:

Seleccione una:
* a. Período de retorno
* b. VAN
* c. TIR
* d. Ninguna de las anteriores.

In [14]:
# p10- c

# Intro to Financial Concepts using Python from DataCamp
https://datascience103579984.wordpress.com/2019/09/19/intro-to-financial-concepts-using-python-from-datacamp/

## 1. The Time Value of Money

In [15]:
# Calculate the future value (cumulative return) of a $100 investment 
# which grows at a rate of 6% per year for 30 years in a 
# row and assign it to future_value.
# Calculate the future value of the investment and print it out
future_value = 100 * (1 + 0.06) ** 30
print("Future Value of Investment: " + str(round(future_value, 2)))
#  Future Value of Investment: 574.35

Future Value of Investment: 574.35

In [16]:
# Another important variable is the number of compounding periods, 
# which can greatly affect 
# compounded returns over time.
# Predefined variables
initial_investment = 100
growth_periods = 30
growth_rate = 0.06
 
# Calculate the value for the investment compounded once per year
compound_periods_1 = 1
investment_1 = initial_investment*(1 + growth_rate / compound_periods_1)**(compound_periods_1*growth_periods)
print("Investment 1: " + str(round(investment_1, 2)))
 
# Calculate the value for the investment compounded quarterly
compound_periods_2 = 4
investment_2 = initial_investment*(1 + growth_rate / compound_periods_2)**(compound_periods_2*growth_periods)
print("Investment 2: " + str(round(investment_2, 2)))
 
# Calculate the value for the investment compounded monthly
compound_periods_3 = 12
investment_3 = initial_investment*(1 + growth_rate / compound_periods_3)**(compound_periods_3*growth_periods)
print("Investment 3: " + str(round(investment_3, 2)))

Investment 1: 574.35
Investment 2: 596.93
Investment 3: 602.26

In [17]:
# Calculate the future value of a $100 investment that depreciates in value by 5% 
# per year for 10 years and assign it to future_value.
# Calculate the future value
initial_investment = 100
growth_rate = -0.2
growth_periods = 10
future_value = initial_investment*(1 + growth_rate)**(growth_periods)
print("Future value: " + str(round(future_value, 2)))
 
# Calculate the discount factor
discount_factor = 1/((1 + growth_rate)**(growth_periods))
print("Discount factor: " + str(round(discount_factor, 2)))
 
# Derive the initial value of the investment
initial_investment_again = future_value * discount_factor
print("Initial value: " + str(round(initial_investment_again, 2)))

Future value: 10.74
Discount factor: 9.31
Initial value: 100.0

In [18]:
# The .pv(rate, nper, pmt, fv) function, for example, allows you to calculate the present value of an investment as before with a few simple parameters:

# rate: The rate of return of the investment
# nper: The lifespan of the investment
# pmt: The (fixed) payment at the beginning or end of each period (which is 0 in our example)
# fv: The future value of the investment
# You can use this formula in many ways. For example, you can calculate the present value of future investments in today’s dollars.

# Compute the present value of an investment which will yield 
# $10,000 15 years from now at an inflation rate of 3% 
# per year and assign it to investment_1.


investment_1 = np.pv(rate=0.03, nper=15, pmt=0, fv=10000)
 
# Note that the present value returned is negative, so we multiply the result by -1
print("Investment 1 is worth " + str(round(-investment_1, 2)) + " in today's dollars")
 
# Calculate investment_2
investment_2 = np.pv(rate=0.05, nper=10, pmt=0, fv=10000)
print("Investment 2 is worth " + str(round(-investment_2, 2)) + " in today's dollars")
 
# Investment 1 is worth 6418.62 in today's dollars
# Investment 2 is worth 6139.13 in today's dollars

Investment 1 is worth 6418.62 in today's dollars
Investment 2 is worth 6139.13 in today's dollars

In [19]:
# Future Value
# The numpy module also contains a similar function, .fv(rate, nper, pmt, pv), which allows you to calculate the future value of an investment as before with a few simple parameters:

# rate: The rate of return of the investment
# nper: The lifespan of the investment
# pmt: The (fixed) payment at the beginning or end of each period (which is 0 in our example)
# pv: The present value of the investment
# It is important to note that in this function call, you must pass a negative value into the pv parameter if it represents a negative cash flow (cash going out). In other words, if you were to compute the future value of an investment, requiring an up-front cash payment, you would need to pass a negative value to the pv parameter in the .fv() function.
# Calculate investment_1
investment_1 = np.fv(rate=0.01, nper=15, pmt=0, pv=-10000)
print("Investment 1 will yield a total of $" + str(round(investment_1, 2)) + " in 15 years")
 
# Calculate investment_2
investment_2 = np.fv(rate=0.08, nper=15, pmt=0, pv=-10000)
print("Investment 2 will yield a total of $" + str(round(investment_2, 2)) + " in 15 years")
 
#

Investment 1 will yield a total of $11609.69 in 15 years
Investment 2 will yield a total of $31721.69 in 15 years

In [20]:
# NPV , IRR
# Net Present Value , Internal rate of return and Cash Flows
# Discounting Cash Flows
# You can use numpy’s net present value function numpy.npv(rate, values) to calculate the net present value of a series of cash flows. 

# Predefined array of cash flows
cash_flows = np.array([100, 100, 100, 100, 100])
 
# Calculate investment_1
investment_1 = np.npv(rate=0.03, values=cash_flows)
print("Investment 1's net present value is $" + str(round(investment_1, 2)) + " in today's dollars")
 
# Calculate investment_2
investment_2 = np.npv(rate=0.05, values=cash_flows)
print("Investment 2's net present value is $" + str(round(investment_2, 2)) + " in today's dollars")
 
# Calculate investment_3
investment_3 = np.npv(rate=0.07, values=cash_flows)
print("Investment 3's net present value is $" + str(round(investment_3, 2)) + " in today's dollars")

Investment 1's net present value is $471.71 in today's dollars
Investment 2's net present value is $454.6 in today's dollars
Investment 3's net present value is $438.72 in today's dollars

In [21]:
# Predefined array of cash flows
cash_flows = np.array([3100, 3100,3100,3100,3100,])
 
# Calculate investment_1
investment_1 = np.npv(rate=0.1, values=cash_flows)
print("Investment 1's net present value is $" + str(round(investment_1, 2)) + " in today's dollars")

Investment 1's net present value is $12926.58 in today's dollars

In [22]:
# van y tir
initialInvestment   = -12250; # Negative, since it results in an outflow of cash
ahorro=3100
cashFlows           = [initialInvestment, ahorro, ahorro,ahorro,ahorro,ahorro,];
discountRate    = 0.1; # Nine percent per annum
# VAN
# Net Present Value
npv             = round(np.npv(discountRate, cashFlows),1);  
# TIR
# Calculate the IRR
irr = round(np.irr(cashFlows)*100,1);
# 
print("Net present value of the investment:%3.2f"%npv);
print("Internal rate of return:%3.1f"%irr);

Net present value of the investment:-498.60
Internal rate of return:8.4

# solucion

Comenzado el	Monday, 2 de November de 2020, 20:55
Estado	Finalizado
Finalizado en	Wednesday, 4 de November de 2020, 11:41
Tiempo empleado	1 día 14 horas
Calificación	10,00 de 10,00 (100%)
## Pregunta 1
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
Una empresa de servicios energéticos es aquella empresa que...

    Seleccione una:
    a. Genera energía eléctrica
    b. Invierte en eficiencia energética y recupera parte de  inversión de los ahorros. Correcta
    c. Es un banco.
    d. Ninguna de las anteriores.
    Retroalimentación

La respuesta correcta es: Invierte en eficiencia energética y recupera parte de  inversión de los ahorros.
## Pregunta 2
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
En la descripción técnica de una MAES encontraremos:

Seleccione una o más de una:

    a. Los kWh ahorrados.
    b. La ficha técnica de los equipos consumidores de energía que contiene la mejora. Correcta
    c. La inversión de la MAE Correcta
    d. El VAN de la inversión.
    e. Emplazamiento de la mejora Correcta
Retroalimentación
Las respuestas correctas son: La ficha técnica de los equipos consumidores de energía que contiene la mejora., La inversión de la MAE, Emplazamiento de la mejora
Pregunta 3
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
¿Qué inversión supone una caldera de biomasa de pellets generica de 60kW?

Accesorios para el sistema de mando: Ninguno.

Alimentación: Déposito con sistema de aspiración.

Accesorios: todos excepto presostato.

 

Nota: usar la base de precios de CYPE

    Seleccione una:
    a. 17.326€ Correcta
    b. 11.220€
    c. 18.560€
    d. 12.000€
Retroalimentación
La partida es la ICQ015



 

 

 

La respuesta correcta es: 17.326€
## Pregunta 4
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
Tenemos la siguiente propuesta de MAEs

Inversión: 22.000€

Ahorro anual: 8.250€

¿Cuál sería el período de retorno de la inversión?

    Seleccione una:
    a. 2,66 Correcta
    b. 0,37
Retroalimentación

    Período de retorno : 22.000 / 8.250 = 2,66

La respuesta correcta es: 2,66
## Pregunta 5
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
En la MAE anterior tenemos 8.250€ de ahorro anuales. Estos ahorros de 8.250€ generados dentro de 5 años que valor económico tendrían a día de hoy con una tasa del 10%.

    Seleccione una:
    a. 5.123 Correcta
    b. 8.250€
    c. 13.286€
    d. El valor económico es siempre el mismo al largo del tiempo.
Retroalimentación
Valor a dia de hoy: Va = Vf / (1+i)n

    Va = 8.250 / ( 1 + 0.1 )5 = 5.122,6

La respuesta correcta es: 5.123
## Pregunta 6
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
Siguiendo con el ejemplo anterior sabemos que los ahorros duraran 5 años. Calculad el VAN con una tasa de actualización del 10%.

    Seleccione una:
    a. 19.250
    b. 8.250
    c. 9.274 Correcta
    d. 31.274
Retroalimentación
 

        A	 B 
    1	tasa k	0,1
    2	1	           8.250 €
    3	2	           8.250 €
    4	3	           8.250 €
    5	4	           8.250 €
    6	5	           8.250 €
    7	VAN	           9.274 €


  Donde la casilla B7 del VAN es

=VAN(B1,B2:B6) - 22.000 

La respuesta correcta es: 9.274
## Pregunta 7
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
¿Qué valor tiene el TIR de la MAE anterior?

    Seleccione una:
    a. Faltan datos.
    b. Negativo
    c. 9%
    d. 25% Correcta
Retroalimentación
 

 

        A	 B 
    1	Inversión	-       22.000 €
    2	1	           8.250 €
    3	2	           8.250 €
    4	3	           8.250 €
    5	4	           8.250 €
    6	5	           8.250 €
    7	TIR	25%


Dónde la casillas B7 del TIR es:

 

=TIR(B1:B6)

La respuesta correcta es: 25%
## Pregunta 8
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
De los 8.250€ de ahorro anuales un 60% provienen de la electricidad y un 40% del gas natural. ¿Si suponemos que el precio de la electricidad aumentara un 5% anual y el del gas natural un 3% anual, cuál será el nuevo VAN?

Nota: En el ahorro del primer año ya teneis que aplicar el aumento.

 

    Seleccione una:
    a. 13.954€
    b. 13.178€ Correcta
    c. 12.965€
    d. El VAN será el mismo que el apartado anterior.
Retroalimentación
A día de hoy el ahorro en electricidad es de 4.950€ y en combustible de 3.300€. El primer paso es aplicar los incrementos anuales del 5% y 3% a cada parte del coste. El incremento es anual, por lo que por ejemplo en electricidad el cuarto año es 1,05 x 1,05 x 1,05 x 1,05 = 1,215 no 1,2.

 

        Electricidad	Combustible	 
        Coste	Incremento 	Coste	Incremento 	Total
    Año 1	          5.198 €	1,050	           3.399 €	1,03	          8.597 €
    Año 2	          5.457 €	1,102	           3.501 €	1,06	          8.958 €
    Año 3	          5.730 €	1,157	           3.606 €	1,09	          9.336 €
    Año 4	          6.017 €	1,217	           3.714 €	1,13	          9.731 €
    Año 5	          6.318 €	1,276	           3.826 €	1,16	       10.143 €


Una vez tenemos los coste del ahorro en los próximos años podemos calcular VAN  en la casilla A8=VNA(B2;B3:B7)+B1

 

        A	B
    1	Inversión	-      22.000 €
    2	tasa k	0,1
    3	1	          8.597 €
    4	2	          8.958 €
    5	3	          9.336 €
    6	4	          9.731 €
    7	5	       10.143 €
    8	VAN	       13.178 €

La respuesta correcta es: 13.178€
## Pregunta 9
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
Por último, si a los ahorros resultantes de la pregunta anterior les aplicamos un 35% de impuestos que VAN tendríamos.

    Seleccione una:
    a. 865,4€ Correcta
    b. Un VAN negativo.
    c. 15.124€
    d. 4.157€
Retroalimentación
 Aplicamos el 35% de impuestos sobre los ahorros calculados en el apartado anterior:

 

        Sin impuestos	Con impuestos
    Año 1	          8.597 €	    5.587,73 €
    Año 2	          8.958 €	    5.822,92 €
    Año 3	          9.336 €	    6.068,56 €
    Año 4	          9.731 €	    6.325,11 €
    Año 5	       10.143 €	    6.593,08 €
 Y ahora calculamos el VAN sobre estos nuevos ahorros con la misma fórmula que antes.

 

    Inversión	-      22.000 €
    tasa k	10%
    1	          5.588 €
    2	          5.823 €
    3	          6.069 €
    4	          6.325 €
    5	          6.593 €
    VAN	             865 €

La respuesta correcta es: 865,4€
## Pregunta 10
Correcta
Puntúa 1,00 sobre 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
Para comparar dos inversiones de un cambio de luminarias utilizaremos:

    Seleccione una:
    a. Período de retorno
    b. VAN
    c. TIR Correcta
    d. Ninguna de las anteriores.
Retroalimentación
La respuesta correcta es: TIR