En esta segunda parte del caso práctico vamos a realizar una parte del inventario energético y a interpretar los
resultados de las mediciones experimentales.
## Datos Recogidos
Tenemos los siguientes datos que hemos recogido de la visita en el centro cívico.

1. Alumbrado: Inventario de aparatos de alumbrado. Medida luminotécnicas de las salas representativas.
2. Envolvente: Plano constructivo con la definición de los cerramientos.
3. Sistema eléctrico: Medición del factor (phi)
4. Climatización: Ficha técnicas de algunos modelos, fotos y referencias de algunos otros. Medida caudal
de la enfriadora y de combustión de la caldera.
5. Bombas: Modelos de diferentes bombas y motores.
6. Tuberías: Mediciones de grosores y medición de los tramos de tuberías sin aislamiento.
Todos estos datos los podéis encontrar en la carpeta de Inventario-Mediciones.

## Ejercicio a realizar
Los ejercicios a realizar los encontraréis en el cuestionario del caso práctico del moddle. Para practicar antes de realizar el
cuestionario podéis intentar contestar las siguientes preguntas:
1. Practicad rellenando diferentes fichas del inventario. Podéis usar la tipología de fichas que os he
dejado como ejemplo o las que creéis vosotros.
2. Calcular los VEEI de los locales.
3. Calcular la transmitancia térmica de los cerramientos.
4. Determinar si es necesario cambiar la batería de condensadores. ¿Pagaremos recargo?
5. ¿Cuál es el EER de la enfriadora según las mediciones?
6. ¿Cuál es el rendimiento de la caldera según análisis de combustión?
7. ¿Si aislamos las tuberías según RITE que ahorro tendríamos?

Auditorías energéticas
Ruta a la página
Área personal / ►Mis cursos / ►Auditorías energéticas / ►Caso Práctico / ►Cuestionario de autoevaluación del caso práctico - parte 2
# Pregunta 1
Sin responder aún
Puntúa como 1,00
No marcadasMarcar pregunta
Enunciado de la pregunta
¿Cúal es el VEEI de cada local?

Vestíbulo

Respuesta 1
Elegir...
Sala Ensayo

Respuesta 2
Elegir...
Aula 4 - Taller

Respuesta 3
Elegir...
Sala reuniones

Respuesta 4
Elegir...
Bar

Respuesta 5
Elegir...


entre

2.8

2.4

3.4

6.4

6.1

In [149]:
# /respuesta pregunta 1//////////////////////
#  definir en las tablas las variables
import numpy as np
import pandas as pd
import datetime

pd.options.mode.chained_assignment = None  # default='warn'
import matplotlib.pyplot as plt
import base64
from io import BytesIO


# ls datos/efe*.*
df=pd.DataFrame()
# CTE-HE3 Tabla 2.1 del CTE-HE3 con los VEEI límites permitidos
VEEI_límites=pd.read_csv("veei.csv", index_col=0, header=0)
# CTE-HE3 Tabla 2.2 CTE-HE3 con la potencia máxima instalada permitada
pmip=pd.read_csv("Potencia_máxima_iluminación.csv", header=0)

# 2./Calcular los VEEI de los locales

# Vamos a calcular el VEEI 
# VEEI = P  x 100 / S x Em
#  El P es el consumo de la luminaria (de la lámpara + equipo auxiliar), en la tabla de la página 105 encontrareis que el consumo de una campana de 150W de halogenuros es de 171W.
#  VEEI = 52 x 171  x 100 /  500 x 348.75 = 5,1
# El valor es superior al de normativa que es 5 según tabla de la página 178 por lo tanto no cumple el VEEI.
# En el ratio de  potencia instalada es de: 52 x 171 / 500 = 17,8 W/m² por lo que no cumple el valor de 15 de la tabla de la página 178.
# La respuesta correcta es: Ninguno de los dos.

df=pd.read_csv("iluminacion.csv", header=0)
df=df[df.Local.str.contains("Vestíbulo") | df.Local.str.contains("Sala Ensayo") | df.Local.str.contains("Aula 4") | df.Local.str.contains("reuniones") | df.Local.str.contains("Bar")]
df['conbalastro']=[32,64,64,32,32]

# df

# asignacjion de veei max
df['veei_max']=0
df["veei_max"]=np.where(df.Local.str.contains("Aula") & (df["veei_max"]==0),3.5,df["veei_max"])
df["veei_max"]=np.where(df.Local.str.contains("Sala") & (df["veei_max"]==0),8.0,df["veei_max"])
df["veei_max"]=np.where(df.Local.str.contains("Bar") & (df["veei_max"]==0),8.0,df["veei_max"])
df["veei_max"]=np.where(df.Local.str.contains("Vestíbulo") & (df["veei_max"]==0),4.0,df["veei_max"])
df["veei_max"]=np.where(df.Local.str.contains("Despacho") & (df["veei_max"]==0),3.0,df["veei_max"])
df["veei_max"]=np.where(df.Local.str.contains("Rocódromo") & (df["veei_max"]==0),8.0,df["veei_max"])
df["veei_max"]=np.where(df.Local.str.contains("Pasadizo") & (df["veei_max"]==0),4.0,df["veei_max"])


# asignacion de P max
df['p_max']=0
df["p_max"]=np.where(df.Local.str.contains("Aula") &      (df["p_max"]==0),15,df["p_max"])
df["p_max"]=np.where(df.Local.str.contains("Sala") &      (df["p_max"]==0),15,df["p_max"])
df["p_max"]=np.where(df.Local.str.contains("Bar") &       (df["p_max"]==0),18,df["p_max"])
df["p_max"]=np.where(df.Local.str.contains("Vestíbulo") & (df["p_max"]==0),10,df["p_max"])
df["p_max"]=np.where(df.Local.str.contains("Despacho") &  (df["p_max"]==0),12,df["p_max"])
df["p_max"]=np.where(df.Local.str.contains("Rocódromo") & (df["p_max"]==0),15,df["p_max"])
df["p_max"]=np.where(df.Local.str.contains("Pasadizo") &  (df["p_max"]==0),5,df["p_max"])

df['pp']=df.udp*df.conbalastro*df.Unidades
df['veei']=df.pp*100/df.Área/df.Em
df['p']=df.pp/df.Área
vv=['Local','veei_max','veei','cumple_v','p_max','p','cumple_p']
# ddff=df[df.Local.str.contains("Vestíbulo") | df.Local.str.contains("Sala Ensayo") | df.Local.str.contains("Aula 4") | df.Local.str.contains("reuniones") | df.Local.str.contains("Bar")]
df

,Planta,Local,Tipo,udp,Potencia,Unidades,Balastro,Área,Em,conbalastro,veei_max,p_max,pp,veei,p
0,baja,Vestíbulo,Donlight,2,26,5,Electromagnético de bajas pérdidas,33,151,32,4.0,10,320,6.421834,9.696970
3,baja,Sala Ensayo,Fluorescentes,1,58,2,Electromagnético de bajas pérdidas,10,380,64,8.0,15,128,3.368421,12.800000
7,sotano,Aula 4,Fluorescentes,2,58,4,Electromagnético de bajas pérdidas,71,299,64,3.5,15,512,2.411795,7.211268
10,primera,Sala reuniones,Donlight,2,26,4,Electromagnético de bajas pérdidas,18,501,32,8.0,15,256,2.838767,14.222222
14,Bar,Bar,Fluorescentes,2,26,11,Electromagnético de bajas pérdidas,51,225,32,8.0,18,704,6.135076,13.803922

# Respuesta 1

https://www.codigotecnico.org/pdf/Documentos/HE/DcmHE.pdf

## Sección HE 3  Eficiencia Energética de las Instalaciones de Iluminación 

### Caracterización y cuantificación de las exigencias 2.1 
#### Valor de Eficiencia Energética de la Instalación 1    
La eficiencia energética de una  instalación  de  iluminación de una  zona, se  determinará mediante el valor de eficiencia energética de la instalación VEEI (W/m2) por cada 100  lux mediante la siguienteexpresión: 

$$
VEEI=\frac{100 P}{S E_m}
$$

siendo:
* P  la potencia de la lámpara más el equipo auxiliar [W]; 
* S la superfície iluminada [m2]; 
* $E_m$ la iluminancia media horizontal mantenida [lux] 


Los  valores  de  eficiencia  energética  límite  en  recintos  interiores  de  un  edificio  se  establecen  en  la tabla 2.1. Estos valores incluyen la iluminación general y la iluminación de acento, pero no las insta-laciones de iluminación de escaparates y zonas expositivas. Tabla 2.1 Valores límite de eficiencia energética de la instalación 

{{VEEI_límites}}


* (1)Incluye la instalación de iluminación general de salas como  salas de examen general, salas de emergencia, salas de escaner y radiología,  salas  de  examen  ocular  y  auditivo  y  salas  de  tratamiento.  Sin  embargo  quedan  excluidos  locales  como  las  salas  de operación,  quirófanos,  unidades  de  cuidados  intensivos,  dentista,  salas  de  descontaminación,  salas  de autopsias  y  mortuorios  y otras salas que por su actividad puedan considerarse como salas especiales.  
* (2)  Incluye la instalación de iluminación del aula y las pizarras de las aulas de enseñanza, aulas de práctica de ordenador, música, laboratorios de lenguaje, aulas de dibujo técnico, aulas de prácticas y laboratorios, manualidades, talleres de enseñanza y aulas de arte, aulas de preparación y talleres, aulas comunes de estudio y aulas de reunión, aulas clases nocturnas y educación de adultos, salas de lectura, guarderías, salas de juegos de guarderías y sala de manualidades.  
* (3) Incluye la instalación de iluminación interior de la habitación y baño, formada por iluminación general, iluminación de lectura e iluminación para exámenes simples. 
* (4)  Espacios  utilizados  por  cualquier  persona  o  usuario,  como  recibidor,  vestíbulos,  pasillos,  escaleras,  espacios  de  tránsito  de personas, aseos públicos, etc.  
* (5)Incluye  las  instalaciones  de  iluminación  del  terreno  de  juego  y  graderíos  de  espacios  deportivos,  tanto  para  actividades  de entrenamiento y competición, pero no se incluye las instalaciones de iluminación necesarias para las retransmisiones televisadas.   Los graderíos serán asimilables a zonas comunes del grupo 1 
* (6) Espacios  destinados  al  tránsito  de  viajeros  como  recibidor  de  terminales,  salas  de  llegadas  y  salidas de  pasajeros,  salas  de recogida de equipajes, áreas de conexión, de ascensores, áreas de mostradores de taquillas, facturación e información, áreas de espera, salas de consigna, etc. 
* (7)   Incluye  la  instalación  de iluminación  general  e iluminación  de  acento  de  recibidor,  recepción,  pasillos,  escaleras,  vestuarios  y aseos de los centros comerciales.
* (8)   Incluye  los  espacios  destinados  a  las  actividades  propias  del  servicio  al  público  como  recibidor,  recepción,  restaurante,  bar,  comedor, auto-servicio o buffet, pasillos, escaleras, vestuarios, servicios, aseos, etc. 
* (9) Incluye la instalación de iluminación general e iluminación de acento. En el caso de cines, teatros,  salas de conciertos, etc. se excluye la iluminación con fines de espectáculo, incluyendo la representación y el escenario. 


## Potencia instalada en edificio 
1 La potencia instalada en iluminación, teniendo en cuenta la potencia de lámparas y equipos auxi-liares, no superará los valores especificados en la Tabla 2.2. 

Tabla 2.2 Potencia máxima de iluminación



{{pmip}}

{{df}}

# Pregunta 2

Todos los locales cumplen con los requisitos de VEEI y W/m² del CTE.

Seleccione una:
Verdadero
Falso

In [82]:
# espuesta pregunta 2
df['cumple_p']=df.veei<df.veei_max
df['cumple_v']=df.p<df.p_max
# df[vv]

# Pregunta 2
nop=df[df["cumple_p"]==False]
noveei=df[df["cumple_v"]==False]

## Respuesta pregunta 2
### no cumple la condicion de VEEI
{{noveei}}
### no cumple la condicion de potencia

{{nop}}

# Pregunta 3

Tenemos las siguientes superficies de envolvente


Fachada exterior 1         : 500 m²

Fachada exterior 2         : 250 m²

Forjado general al exterior: 50  m²

Forjado salas al exterior  : 10  m²

Cubierta                   : 375 m²


¿Cual es la energía que perdemos en calefacción si el edificio está situado en una localidad con 2.166 GdC anual?

Nota: la solución sin decimales y en kWh/año.

In [1]:
# ===============================================================
# 
ddf=pd.DataFrame()
# ddf['definiciones']=['espesor','conductividad térmica','resistencia','transmitancia']
# ddf['relaciones'] = ['e', '$\lambda$','e/$\lambda$', '1/R']
# ddf['Uds'] = ['mm', 'W/(m*C)','m$^2$C/W', 'W/($m^2$C)']

ddf['e']=['espesor', 'L','mm']
ddf['Q']=['calor','E','Ws']
ddf['q']=['Flujo calor','$\Delta Q / \Delta t$','W']
ddf['$\lambda$=k']=['Conductividad termica','q/(e T)','W/(m C)']
ddf['R']=['resistencia termica','e/$\lambda$','$m^2 C/W$']
ddf['U']=['Transmitancia termica','1/R=$\lambda$/e','$W/(m^2 C)$']

# ===============================================================
columns=['Rse','Rsi']
index=['vertical','horizontal','horizontaldescendente']
rs=pd.DataFrame(index=index,columns=columns)

rs['Rse']=[0.04,0.04,0.04]
rs['Rsi']=[0.13,0.10,0.17]
# ===============================================================
# ==========================

# para cada superficie
envolvente=pd.read_csv("envolvente.csv",  header=0)
envolvente['$\lambda$']=0.2
envolvente['R']=dd['e']/dd['$\lambda$']


# paa la envolvente
GdC=2166 # 
RR=envolvente.groupby(['envolvente']).sum().R

tt=pd.DataFrame(RR)
tt['Rt']=rs.at['horizontal','Rsi']+RR+rs.at['horizontal','Rse']
# R
# tt['U']=1/tt.Rt
tt['U']=0.2
tt['S']=[500,250,50,10,375]
# 
GD=1005
tt['q']=round(tt.U*tt.S*GD*24/1000,3 ) # w/m2/c m2 (d*c) 24h/d 1k/1000

Energia_que_perdemos_en_calefacción=tt.sum().q
# df

NameError: name 'pd' is not defined

##  respuesta pregunta 3  !!!!! faltan ls lambdas de los materiales BDD
https://www.codigotecnico.org/pdf/GuiasyOtros/Guia_aplicacion_DBHE2019_Ejemplos_I.pdf

# 2. CÁLCULO DE TRANSMITANCIAS

## Inicio

1. Transmitancias de cerramientos en contacto con el exterior
2. Transmitancias de particiones interiores


Se va a realizar a continuación a modo de ejemplo el cálculo de varios cerramientos, un caso general
de contacto con el exterior y varios cerramientos singulares de contacto con espacios no habitables
que aparecen en las diferentes opciones de estudio.

## 1. Transmitancias de cerramientos en contacto con el exterior

Se tratará normalmente de cerramientos compuesto de varias “hojas” y diferentes materiales. De manera
general mediante el inverso de la suma de las resistencias térmicas de cada capa más las resistencias
térmicas superficiales en ambas caras del cerramiento, obtenemos el valor de la transmitancia para el
conjunto (U):
Su cálculo, se describe detalladamente en el documento de ayuda DA DB-HE / 1. Cálculo de parámetros
característicos de la envolvente. De manera resumida, exponemos a continuación los pasos básicos
para dos ejemplos concretos de nuestro modelo.
Para los cerramientos opacos en contacto con el aire exterior, su transmitancia se obtiene directamente
mediante la expresión:

$$
U=\frac{1}{R_T}
$$

siendo,

$R_T$ la resistencia térmica total del componente constructivo [$m^2$·K/ W].

Por otra parte:

$R_T = R_{si} + R_1 + R_2 +...+ R_n + R_{se} (2)$

siendo,

$R_1, R_2...R_n$ las resistencias térmicas de cada capa definidas según la expresión (3) [m2·K/ W];

$R_{si}$ y $R_{se}$ las resistencias térmicas superficiales correspondientes al aire interior y exterior respectivamente, tomadas de la Tabla 1 Resistencias térmicas superficiales de cerramientos en contacto con el aire exterior [m2 ·K/ W]de acuerdo con la posición del cerramiento, dirección del flujo de calor y su situación en el edificio [m2·K/ W].

La resistencia térmica de una capa térmicamente homogénea viene definida por la expresión:

$$
R=\frac{e}{\lambda}
$$

siendo,

e el espesor de la capa [m]. En caso de una capa de espesor variable se considera el espesor medio;

$\lambda$ la conductividad térmica de diseño del material que compone la capa, que se puede calcular a partir de los valores térmicos declarados según la norma UNE-EN 10456:2012.

En el caso de materiales heterogéneos, como las fábricas, se puede considerar la conductividad
equivalente del conjunto.

Para los cerramientos en contacto con el terreno, la transmitancia intrínseca del cerramiento ha de ser corregida por el efecto del terreno. Para ello:

* Suelos: se puede aplicar la Tabla 3 Transmitancia térmica US [W/$m^2$ ·K] para soleras o losas
apoyadas sobre el nivel del terreno o como máximo 0,50 m por debajo de éste, o la Tabla 4 Transmitancia térmica US [W/$m^2$·K] para soleras o losas a una profundidad superior a 0,5 m respecto al nivel del terreno
* Muros o pantallas: se obtiene de la Tabla 5 Transmitancia térmica de muros enterrados UT
[W/$m^2$·K] en función de su profundidad z, y de la resistencia térmica del muro.
* Cubiertas: La transmitancia térmica UT [W/$m^2$ ·K] de las cubiertas enterradas se obtiene mediante el procedimiento general descrito anteriormente para cerramientos en contacto con el aire
exterior, considerando el terreno como otra capa térmicamente homogénea de conductividad
λ=2 W/m·K.

En primer lugar, nos ocupamos del cálculo del muro exterior cuya composición se emplea en todas las
configuraciones de estudio




#### Cálculo de la U

Hay diferentes métodos experimentales para el cálculo de la U. Dos de ellos són:

- Utilización de una cámara termográfica
- Utilización de un equipo multifunción con sonda U.

La camara termográfica nos servirá también para detectar posibles puentes térmicos o discontinuidades de aislamento.
 


## demanda energetica en envolvente
definido,

{{ddf}}


$q=\frac{\Delta Q}{\Delta t}=\frac{k*dA*dT}{dx}=\frac{A*\Delta T}{R}=U*A*\Delta T $ ;dado en ( W=J/s )


Si en lugar del $\Delta T$ usamosl los GD ano

$q=U*A*GD*24$; dado en ( kwh/ano )S


En  el  caso  de  materiales  heterogéneos,  como  las  fábricas,  se  puede  considerar  la conductividad equivalente del conjunto.

Para los cerramientos en contacto con el terreno, la transmitancia intrínseca del cerramiento ha de ser corregida por el efecto del terreno. Para ello: 
* Suelos: se  puede  aplicar  la Tabla  3  Transmitancia  térmica  US[W/m2·K] para  soleras  o  losas apoyadas  sobre  el  nivel  del  terreno  o  como  máximo  0,50 mpor  debajo  de  éste,ola Tabla  4 Transmitancia  térmica  US[W/m2·K]para soleras  o  losas  a  una  profundidad  superior  a  0,5  m respecto al nivel del terreno
* Muros  o pantallas: se  obtiene  de  laTabla  5  Transmitancia  térmica  de  muros  enterrados  UT[W/m2·K]en función de su profundidad z, y de la resistencia térmica del muro.
* Cubiertas: La transmitancia térmica UT[W/m2·K] de las cubiertas enterradas se obtiene mediante el  procedimientogeneral  descrito  anteriormente  para  cerramientos  en  contacto  con  el  aire exterior, considerando el terrenocomo otra capa térmicamente homogénea de conductividad λ=2 W/m·K.

En primer lugar, nos ocupamos del cálculo del muro exterior cuya composición se emplea en todas las configuracionesde estudio.

{{dd}}

### componentes de la envolvente

La transmitancia térmica U [W/m2K] se calcula aplicandola las expresones anteriores

> Energia que perdemos en calefacción= {{energia_que_perdemos_en_calefacción}} kWh/año


en particular para cada uno de las superficies dela envolvente
{{tt}}

# Pregunta 4 verdadero

¿Es necesario cambiar la batería de condensadores?

Seleccione una:
Verdadero
Falso

## Respuesta
hay picos por debajo de 0.8

# Pregunta 5 2.64 y 2.14

¿Cual es el rendimiento de la planta enfriadora?

 a) Según placa de características: Respuesta 2.64

 b) Según medición caudalímetro si el consumo eléctrico medio durante la medición fue de 17,5kW  Respuesta 2.14

Nota 1: Usad dos decimales.

Nota 2: Para el cálculo del EER por las mediciones realizad un EER medio durante todo el rango de datos. Usando la formula de la página 200 para la potencia frigorífica y un salto térmico de 4,9ºC.

Pot (kW) = Caudal (litros/minuto) x 60 min/hora x DT (ºC) / 860 kcalh/kW)

In [120]:
#### Respuesta 5 pag 183

# Pot (kW) = Caudal (litros/minuto) x 60 min/hora x DT (ºC) / 860 kcalh/kW)
#
qq=pd.read_csv("Datosmedicióncaudalimetroenfriadora.csv")
m3h=qq.mean().measure #m3/h
lm=m3h*1000/60

DT=4.9 
# 
Pot= lm  * 60  * DT / 860 

df=pd.DataFrame()
df['termica']=[
51 ,
71,
112,
Pot
]

df['electrica']=[
17,
20,
32,
17.5
]

df['EER']=df.termica/df.electrica


# dd
# potencia térmica que pasa por la tubería.

# Pot (kW) = caudal (litros/minuto) x 60 min/hora x DT (oC) / 860 kcalh/kW)
# df['termica']=df.caudal*60*(df.Tretorno-df.Timpulsion)/860

# df['EER']=df.termica/df.electrica

df

     termica  electrica       EER
0   51.00000       17.0  3.000000
1   71.00000       20.0  3.550000
2  112.00000       32.0  3.500000
3   37.47093       17.5  2.141196

# Pregunta 6  84.8

¿Cuál es la potencia mínima que proporciona la caldera según la placa de características?

Respuesta:

# Pregunta 7

¿Cuáles son los siguientes datos de la caldera según el análisis de combustión?

 a) Exceso de aire:  Respuesta  2.33

 b) Rendimiento (%):  Respuesta 89.1

 c) Contenido de CO (ppm):  Respuesta  48

 

 

# Pregunta 8

¿Qué datos podéis encontrar de la bomba UPS de Grundfoss?

 a) Alimentación (V) 230 o 400V Respuesta  230

 b) Clase energética  Respuesta D

 c) Potencia máxima consumida (W) Respuesta 240

 

# Pregunta 9

¿Qué diámetro de aislamiento tendríamos que colocar en las tuberías que no están aisladas para cumplir la normativa actual?

Respuesta en mm

Para la tubería de PP20

Respuesta 1
Elegir...
Para la tubería de PP25

Respuesta 2
Elegir...
Para la tubería de PP40

Respuesta 3
Elegir...
# Pregunta 10

¿Que datos podemos encontrar de la máquina exterior VRV de Mitsubishi?

Nota: encontrareis los datos en http://www.mitsubishitech.co.uk/

Pista: Es del año 2014...

Potencia frío (kW) 13.77

Respuesta 1 3.73
Elegir...
EER

Respuesta 2
Elegir...
COP

Respuesta 3
Elegir...
Potencia Calor (kW)

Respuesta 4
Elegir...
Altura de la máquina (mm)

Respuesta 5
Elegir...
Caudal Exterior aire (m3/min)

Respuesta 6
Elegir...

# solucion

Cuestionario de autoevaluación del caso práctico - parte 2
Comenzado el	Monday, 26 de October de 2020, 11:09
Estado	Finalizado
Finalizado en	Tuesday, 3 de November de 2020, 01:42
Tiempo empleado	7 días 14 horas
Calificación	8,00 de 10,00 (80%)
## Pregunta 1
    Correcta
    Puntúa 1,00 sobre 1,00
    No marcadasMarcar pregunta
    Enunciado de la pregunta
    ¿Cúal es el VEEI de cada local?

    Vestíbulo

    Respuesta 1
    6,4
     Correcta
    Sala Ensayo

    Respuesta 2
    3,4
     Correcta
    Aula 4 - Taller

    Respuesta 3
    2,4
     Correcta
    Sala reuniones

    Respuesta 4
    2,8
     Correcta
    Bar

    Respuesta 5
    6,1
     Correcta
    Retroalimentación
    La respuesta correcta es: Vestíbulo → 6,4, Sala Ensayo → 3,4, Aula 4 - Taller → 2,4, Sala reuniones → 2,8, Bar → 6,1
## Pregunta 2
    Correcta
    Puntúa 1,00 sobre 1,00
    No marcadasMarcar pregunta
    Enunciado de la pregunta
    Todos los locales cumplen con los requisitos de VEEI y W/m² del CTE.

    Seleccione una:
    Verdadero
    Falso Correcta
    Retroalimentación
    La respuesta correcta es 'Falso'
## Pregunta 3
    Incorrecta
    Puntúa 0,00 sobre 1,00
    No marcadasMarcar pregunta
    Enunciado de la pregunta
    Tenemos las siguientes superficies de envolvente

    Fachada exterior 1: 500 m²
    Fachada exterior 2: 250 m²
    Forjado general al exterior: 50 m²
    Forjado salas al exterior: 10 m²
    Cubierta: 375 m²

    ¿Cual es la energía que perdemos en calefacción si el edificio está situado en una localidad con 2.166 GdC anual?

    Nota: la solución sin decimales y en kWh/año.

    Respuesta:
    13074
    Incorrecta
    Retroalimentación
    La respuesta correcta es: 21336,3
## Pregunta 4
    Correcta
    Puntúa 1,00 sobre 1,00
    No marcadasMarcar pregunta
    Enunciado de la pregunta
    ¿Es necesario cambiar la batería de condensadores?

    Seleccione una:
    Verdadero Correcta
    Falso
    Retroalimentación
    La respuesta correcta es 'Verdadero'
## Pregunta 5
    Correcta
    Puntúa 1,00 sobre 1,00
    No marcadasMarcar pregunta
    Enunciado de la pregunta
    ¿Cual es el rendimiento de la planta enfriadora?

     a) Según placa de características: Respuesta
    2,64
    Correcta


     b) Según medición caudalímetro si el consumo eléctrico medio durante la medición fue de 17,5kW  Respuesta
    2,14
    Correcta


    Nota 1: Usad dos decimales.

    Nota 2: Para el cálculo del EER por las mediciones realizad un EER medio durante todo el rango de datos. Usando la formula de la página 200 para la potencia frigorífica y un salto térmico de 4,9ºC.

    Pot (kW) = Caudal (litros/minuto) x 60 min/hora x DT (ºC) / 860 kcalh/kW)

## Pregunta 6
    Incorrecta
    Puntúa 0,00 sobre 1,00
    No marcadasMarcar pregunta
    Enunciado de la pregunta
    ¿Cuál es la potencia mínima que proporciona la caldera según la placa de características?

    Respuesta:
    84,8
    Incorrecta
    Retroalimentación
    La respuesta correcta es: 78
## Pregunta 7
    Correcta
    Puntúa 1,00 sobre 1,00
    No marcadasMarcar pregunta
    Enunciado de la pregunta
    ¿Cuáles son los siguientes datos de la caldera según el análisis de combustión?

     a) Exceso de aire:  Respuesta
    2,33
    Correcta


     b) Rendimiento (%):  Respuesta
    89,1
    Correcta


     c) Contenido de CO (ppm):  Respuesta
    48
    Correcta


 

 

 

## Pregunta 8
    Correcta
    Puntúa 1,00 sobre 1,00
    No marcadasMarcar pregunta
    Enunciado de la pregunta
    ¿Qué datos podéis encontrar de la bomba UPS de Grundfoss?

     a) Alimentación (V) 230 o 400V Respuesta
    230
    Correcta


     b) Clase energética  Respuesta
    D
    Correcta


     c) Potencia máxima consumida (W) Respuesta
    240
    Correcta


 

 

## Pregunta 9
    Correcta
    Puntúa 1,00 sobre 1,00
    No marcadasMarcar pregunta
    Enunciado de la pregunta
    ¿Qué diámetro de aislamiento tendríamos que colocar en las tuberías que no están aisladas para cumplir la normativa actual?

    Respuesta en mm

    Para la tubería de PP20

    Respuesta 1
    25
     Correcta
    Para la tubería de PP25

    Respuesta 2
    25
     Correcta
    Para la tubería de PP40

    Respuesta 3
    50
     Correcta
    Retroalimentación
    La respuesta correcta es: Para la tubería de PP20 → 25, Para la tubería de PP25 → 25, Para la tubería de PP40 → 50

## Pregunta 10
    Correcta
    Puntúa 1,00 sobre 1,00
    No marcadasMarcar pregunta
    Enunciado de la pregunta
    ¿Que datos podemos encontrar de la máquina exterior VRV de Mitsubishi?

    Nota: encontrareis los datos en http://www.mitsubishitech.co.uk/

    Pista: Es del año 2014...

    Potencia frío (kW)

    Respuesta 1
    50 kW
     Correcta
    EER

    Respuesta 2
    3,23
     Correcta
    COP

    Respuesta 3
    3,83
     Correcta
    Potencia Calor (kW)

    Respuesta 4
    56 kW
     Correcta
    Altura de la máquina (mm)

    Respuesta 5
    1710 mm
     Correcta
    Caudal Exterior aire (m3/min)

    Respuesta 6
    370
     Correcta
    Retroalimentación
    La respuesta correcta es: Potencia frío (kW) → 50 kW, EER → 3,23, COP → 3,83, Potencia Calor (kW) → 56 kW, Altura de la máquina (mm) → 1710 mm, Caudal Exterior aire (m3/min) → 370