In [ ]:
# https://www.dataquest.io/blog/tutorial-time-series-analysis-with-pandas/
# https://machinelearningmastery.com/how-to-load-and-explore-household-electricity-usage-data/
# google pandas energy consumption

In [3]:
# ///////////////////////////////////////////////
#  definir en las tablas las variables
from numpy import *
import pandas as pd
import datetime
import seaborn as sns

pd.options.mode.chained_assignment = None  # default='warn'
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib import pyplot
import base64
from io import BytesIO

# ====================================================
# ====================================================

# crear serie temporal
df=pd.read_csv("datos/energia.csv", header=[0])
df["day"]=1
df['fecha']=pd.to_datetime(df[['year','month','day']])
# df.index=df['fecha']
df=df.set_index('fecha')
df=df.drop(columns=["year","month","day"])
# df['diasemana']=df.index.strftime('%A')
# df['ano'] = df.index.year
# df['Mes'] = df.index.month
df.head()
columnas=df.columns.tolist()
# ====================================================
# ====================================================

# para ir pasando todas las figuras a variables
f, ax = plt.subplots(1)
plt.close()
img = BytesIO()
# ====================================================
# ====================================================
# ====================================================
# ====================================================

# ====================================================
# ====================================================

ax = df[columnas].plot.bar( linestyle='None', figsize=(15, 6), subplots=False)
ax.set_ylabel('KWh');
tt='Consumo mensual por periodos'
# ====================================================
ax = plt.suptitle(tt)
plt.savefig(img, format='png')
img.seek(0)
imgb64 = base64.b64encode(img.getvalue()).decode()
f0 = ('<img src="data:image/png;base64,{}">'.format(imgb64))
plt.close()
# ====================================================


# ====================================================
# ====================================================
# ## tt='estadisticos por periodos'
ax = df[columnas].resample('Y').sum().plot.bar(figsize=(15, 6))
tt='estadisticos por periodos'
# ====================================================
ax = plt.suptitle(tt)
plt.savefig(img, format='png')
img.seek(0)
imgb64 = base64.b64encode(img.getvalue()).decode()
f1 = ('<img src="data:image/png;base64,{}">'.format(imgb64))
plt.close()
# ====================================================


# ====================================================
# ====================================================
# tt='estadisticos por periodos'
ax = df[columnas].boxplot(  figsize=(15, 6),  showmeans=True)
tt='estadisticos por periodos'
# ====================================================
ax.set_ylabel('KWh');
ax = plt.suptitle(tt)
plt.savefig(img, format='png')
img.seek(0)
imgb64 = base64.b64encode(img.getvalue()).decode()
f2 = ('<img src="data:image/png;base64,{}">'.format(imgb64))
plt.close()
# ====================================================


# ====================================================
# ====================================================
# tt='historgramas por periodos'
ax=df[columnas].hist(bins=10,linestyle='None', figsize=(15, 6))
tt='historgramas por periodos'
# ====================================================
ax = plt.suptitle(tt)
plt.savefig(img, format='png')
img.seek(0)
imgb64 = base64.b64encode(img.getvalue()).decode()
f3 = ('<img src="data:image/png;base64,{}">'.format(imgb64))
plt.close()
# ====================================================


# tablas
t01=df[columnas].resample('Y').sum()
t02=df[columnas].resample('Y').sum().apply(lambda x: 100 * x / float(x.sum())).round(1)
t03=df.describe().round(0)

# 2.1.2.1 Análisis consumo eléctrico
## a) Consumo anual

{{f0}}
por anos y periods
{{t01}}
en porcentajes
{{porcentajes}}
{{f1}}
{{t02}}
{{f2}}
{{t03}}

{{f3}}

## **d) Análisis de las curvas de carga eléctricas según mediciones**

In [ ]:


# df


df['dxm'] = pd.DatetimeIndex(df.index).daysinmonth
# df
# df = pd.DataFrame({'date' : pd.date_range('20120101',periods=15,freq='M') })
# df['year'] = df['date'].dt.year
# df['month'] = df['date'].dt.month
# df['days_in_month'] = df['date'].dt.daysinmonth
# df
# df['year'] = df['fecha'].dt.year
# df['fecha']

# df=df[["P1","P2","P3","diasmes"]]
# df
# df.groupby(['fecha']).mean()
# df.describe()
df["P1"]=df.p1+df.p4
df["P2"]=df.p2+df.p5
df["P3"]=df.p3+df.p6

dfa=df[["P1","P2","P3"]]
dfa = dfa.cumsum(axis = 0).iloc[[-1]]
# dfa['$\Sigma{Pi}$']=dfa.P1+dfa.P2+dfa.P3
dfa_d=dfa.describe().round(0)
# dfa_c=dfa.cov()

#anual
tt='Consumo por periodo anual de electricidad del edificio período 2011-12/2012-11'
f, ax = plt.subplots(1)
f.set_figheight(5)
f.set_figwidth(15)
ax= dfa.plot.bar(ax=ax)
ax = plt.suptitle(tt)
ax = plt.ylabel("kwh")


img = BytesIO()
plt.savefig(img, format='png')
img.seek(0)
plot_url = base64.b64encode(img.getvalue()).decode()
dfa_g = ('<img src="data:image/png;base64,{}">'.format(plot_url))
plt.close()

dfat=dfa.T
# dfatt=dfat.rename(columns={'fecha':'a'}, inplace=True)
dfat['Porcentaje'] = round(dfat.iloc[:, 0] /dfat.iloc[:, 0].sum()*100,1)
dfat_p=dfat[['Porcentaje']]
dfat_maximo = dfat['Porcentaje'].max()
dfat_periodo = dfat['Porcentaje'].idxmax()



df["Pi"]=df.P1+df.P2+df.P3
# df


#anual
df["laborable"]=df.p1+df.p2+df.p3
df["festivo"]=df.p4+df.p5+df.p6

dfal=df[["laborable","festivo"]]
dfal = dfal.cumsum(axis = 0).iloc[[-1]]
# dfal['$\Sigma{Pi}$']=dfal.L+dfal.F
dfal_d=dfal.describe().round(0)

tt='Consumo por laboralidad anual de electricidad del edificio período 2011-12/2012-11'
f, ax = plt.subplots(1)
f.set_figheight(5)
f.set_figwidth(15)
ax= dfal.plot.bar(ax=ax)
ax = plt.suptitle(tt)
ax = plt.ylabel("kwh")


img = BytesIO()
plt.savefig(img, format='png')
img.seek(0)
plot_url = base64.b64encode(img.getvalue()).decode()
dfal_g = ('<img src="data:image/png;base64,{}">'.format(plot_url))
plt.close()


dfalt=dfal.T
# dfatt=dfat.rename(columns={'fecha':'a'}, inplace=True)
dfalt['Porcentaje'] = round(dfalt.iloc[:, 0] /dfalt.iloc[:, 0].sum()*100,1)
dfalt_p=dfalt[['Porcentaje']]
dfalt_maximo = dfalt['Porcentaje'].max()
dfalt_periodo = dfalt['Porcentaje'].idxmax()



df["Pi"]=df.P1+df.P2+df.P3
# df



# mensual
tt='Consumo mensual del edificio período 2011-12/2012-11'
dfm=df[["Pi"]]
dfm_d=dfm.describe().round(0)
f, ax = plt.subplots(1)
f.set_figheight(5)
f.set_figwidth(15)
ax= dfm.plot.bar(ax=ax)
ax = plt.suptitle(tt)
ax = plt.ylabel("kwh")

img = BytesIO()
plt.savefig(img, format='png')
img.seek(0)
plot_url = base64.b64encode(img.getvalue()).decode()
dfm_g = ('<img src="data:image/png;base64,{}">'.format(plot_url))
plt.close()

dfmt=dfm
# dfatt=dfat.rename(columns={'fecha':'a'}, inplace=True)
dfmt['Porcentaje'] = round(dfmt.iloc[:, 0] /dfmt.iloc[:, 0].sum()*100,1)
dfmt_p=dfmt[['Porcentaje']]
dfmt_maximo = dfmt['Porcentaje'].max()
dfmt_periodo = dfmt['Porcentaje'].idxmax()
datee = datetime.datetime.strptime(dfmt_periodo, "%Y-%m-%d")
dfmt_mes=datee.month


tt='Consumo total mensual del edificio per período de facturación 2011-12/2012-11'
dfmp=df[['P1','P2','P3']]
dfmp_d=dfmp.describe().round(0)
dfmp_c=dfmp.cov()

f, ax = plt.subplots(1)
f.set_figheight(5)
f.set_figwidth(15)
ax= dfmp.plot.bar(ax=ax)
ax = plt.suptitle(tt)
ax = plt.ylabel("kwh")

img = BytesIO()
plt.savefig(img, format='png')
img.seek(0)
plot_url = base64.b64encode(img.getvalue()).decode()
dfmp_g = ('<img src="data:image/png;base64,{}">'.format(plot_url))
plt.close()


# horario por periodos de facturacion
# tarifa 3.0
valle=8
punta=4
llano=12
# 
df["P1h"]=df.P1*df.dxm/punta
df["P2h"]=df.P2*df.dxm/llano
df["P3h"]=df.P3*df.dxm/valle
dfmh=df[['P1h','P2h','P3h']]
# dfmh

tt='Consumo horario por cada período mensual del edificio per período de facturación 2011-12/2012-11'
dfmh_d=dfmh.describe().round(0)
f, ax = plt.subplots(1)
f.set_figheight(5)
f.set_figwidth(15)
ax = dfmh.plot.bar(ax=ax)
ax = plt.suptitle(tt)
ax = plt.ylabel("kwh")
img = BytesIO()
plt.savefig(img, format='png')
img.seek(0)
plot_url = base64.b64encode(img.getvalue()).decode()
dfmh_g = ('<img src="data:image/png;base64,{}">'.format(plot_url))
plt.close()
dfh=df[['p1','p2','p3']]
# dfh

### 2.1.2.1 Análisis consumo eléctrico

#### **a) Consumo anual**

El primer punto a analizar es la tendencia del consumo anual del edificio  tanto en electricidad como en combustible del último período. El período mínimo es el último año aunque se recomienda estudiar más tiempo para  poder comparar diferentes años.

*Datos a observar/analizar:*

- Tendencia del consumo anual total.
- En el caso de aumento o disminuciones del consumo detectar en que períodos de facturación suceden.
- Cambios de hábitos en el consumo.


{{dfa_g}}



{{dfat_p}}

#### Datos observados:

- En el periodo {{dfat_periodo}} se concentra un {{dfat_maximo}} % del consumo

 

### Por tipo dias laborables o festivos
Grafico  de la suma acumulada de la Serie 
{{dfal_g}}
{{dfalt_p}}

#### Datos observados:

- En los dias {{dfalt_periodo}} se concentra un {{dfalt_maximo}} % del consumo



## b) Consumo mensual
Una vez hemos analizado el consumo anual pasaremos a estudiar la evolución  del consumo mes a mes. 
{{dfm_g}}
Resumen la tendencia central, la dispersión y la forma de la distribución del conjunto de datos,
{{dfm_d}}

#### Datos observados:

- En el mes {{dfmt_mes}} se produce el maximo con un {{dfmt_maximo}} % del consumo


## c) Consumo eléctrico por períodos de facturación
En función de la tarifa eléctrica contratada podremos analizar el consumo  por períodos. En nuestra industria tenemos una tarifa 3.0 por lo que  primero tenemos que identificar los períodos: valle de 8 horas, punta  de 4 horas y las 12 restantes llano. 

La única diferencia al largo del año es al período punta que en invierno  es al atardecer de 18h a 22h y en verano al mediodía de 11h a 15h en el horario de máximo uso de la refrigeración.

{{dfmp_g}}
Resumen la tendencia central, la dispersión y la forma de la distribución del conjunto de datos,
{{dfmp_d}}
El período 2 es el que contiene más horas diarias con 12,  por lo que aunque sea el período con más consumo total, podría no ser el que tiene más consumo hora a hora. Realizando la gráfica de consumo horario por período, dividiendo el consumo de cada mes por el  número de horas de cada período.





{{dfmh_g}}
Resumen la tendencia central, la dispersión y la forma de la distribución del conjunto de datos,
{{dfmh_d}}

#### Datos observados:


- Vemos cómo hay más consumo en el  período 2. El período 3 lógicamente será el de menos consume al ser de  noche y fuera de horario laboral.

# Ejercicio facturación (II)

Con los datos del ejemplo de facturación (https://www.cogitiformacion.es/campus/mod/folder/view.php?id=8734) realizad:

- Una gráfica  donde se vea la proporción economica de: termino de energía, termino de  potencia, IVA e impuesto eléctrico como la de la figura 45.
- Calculad la potencia optimizada y su ahorro anual.
- Con el  consumo total anual entrad en el comparador de tarifas y mirad cual  sería la mejor opción para el año próximo y que coste anual tendría.

 

Para el cálculo de la optimización de potencia contratada siempre se tienen que utilizar los valores a día de hoy. Es importante usar siempre los últimos valores porque estamos calculando un ahorro futuro y son los más similares a los que encontraremos. Además en setiembre de 2013 se triplicaron por lo que los ahorros también. 

Podéis utilizar estos valores para el ejercicio:


• P1: 0,111585986 €/kW día
• P2: 0,066951589 €/kW día
• P3: 0,044634397 €/kW día

 Tenéis una entrada en el foro para poner los resultados, comentarios, conclusiones,...

In [ ]:
# precio potencia
ee1=0.111585986 # €/kW día
ee2=0.066951589 # €/kW día
ee3=0.044634397 # €/kW día


df_modulo=pd.read_csv("datos/efe1-precioconsumo1.csv", index_col=0, header=0)
df["exkwh1"]=df_modulo.exkwh

df_modulo=pd.read_csv("datos/efe1-precioconsumo2.csv", index_col=0, header=0)
df["exkwh2"]=df_modulo.exkwh

df_modulo=pd.read_csv("datos/efe1-precioconsumo3.csv", index_col=0, header=0)
df["exkwh3"]=df_modulo.exkwh


df_modulo=pd.read_csv("datos/efe1-preciopotencia.csv", index_col=0, header=0)
df["exkw"]=df_modulo.exkw
# df
pp=139 #kw
eep=0.087539 # e/(kw dia)

eeimpuesto=1.05113*4.864/100
eedescuentocliente=6/100
eeiva=0.18



df["eeconsumo1"]=df.P1*df.exkwh1
df["eeconsumo2"]=df.P2*df.exkwh2
df["eeconsumo3"]=df.P3*df.exkwh3
df["Termino_de_energia"]=df.eeconsumo1+df.eeconsumo2+df.eeconsumo3


df["Descuento"]=df.Termino_de_energia*eedescuentocliente
df["eefactura"]=df["eeconsumo1"]+df["eeconsumo2"]+df["eeconsumo3"]-df["Descuento"]

df["Termino_de_potencia"]=pp*df.dxm*df.exkw

df["antesimpuesto"]=df.Termino_de_energia-df.Descuento+df.Termino_de_potencia

df["Impuesto_electricidad"]=df["antesimpuesto"]*eeimpuesto

df["eefactura2"]=df["eefactura"]+df["Impuesto_electricidad"]+df["Termino_de_potencia"]

df["IVA"]=df["eefactura2"]*0.18
df["Total"]=df["eefactura2"]+df["IVA"]


# 
# 
dfee=pd.DataFrame()
dfea=pd.DataFrame()
dfem=pd.DataFrame()

dfee=df[["Termino_de_energia","Descuento","Termino_de_potencia","Impuesto_electricidad","IVA"]]
# dfee.round(2)
# 
tt='Costes eléctricos mensuales por conceptos facturados.'
f, ax = plt.subplots(1)
f.set_figheight(5)
f.set_figwidth(15)
ax = dfee.plot.bar(ax=ax,stacked=True)
ax = plt.suptitle(tt)
ax = plt.ylabel("kwh")
img = BytesIO()
plt.savefig(img, format='png')
img.seek(0)
plot_url = base64.b64encode(img.getvalue()).decode()
dcem_g = ('<img src="data:image/png;base64,{}">'.format(plot_url))
plt.close()

# 
tt='Costes eléctricos anuales por conceptos facturados.'

dfa=dfee
dfa = dfa.cumsum(axis = 0).iloc[[-1]]
dfa_d=dfa.describe().round(0)
# dfa_c=dfa.cov()

#anual
f, ax = plt.subplots(1)
f.set_figheight(5)
f.set_figwidth(15)
ax= dfa.plot.bar(ax=ax,stacked=True)
ax = plt.suptitle(tt)
ax = plt.ylabel("kwh")


img = BytesIO()
plt.savefig(img, format='png')
img.seek(0)
plot_url = base64.b64encode(img.getvalue()).decode()
dfa_g = ('<img src="data:image/png;base64,{}">'.format(plot_url))
plt.close()




P1=0.111585986 # €/kW día
P2=0.066951589 # €/kW día
P3=0.044634397 # €/kW día

df_modulo=pd.read_csv("datos/efe1-m1.csv", index_col=0, header=0)
df["pm1"]=df_modulo.kw

df_modulo=pd.read_csv("datos/efe1-m2.csv", index_col=0, header=0)
df["pm2"]=df_modulo.kw

df_modulo=pd.read_csv("datos/efe1-m3.csv", index_col=0, header=0)
df["pm3"]=df_modulo.kw

# df[['pm1','pf1']]
yy=[]
xx=[]
for x in range(1, pp+1):
    pc=x
    df["pf1"]=where(df['pm1'] <  0.85*pc,pc,
                    where((df['pm1'] >= 0.85*pc) & (df['pm1'] <= 1.05*pc),df['pm1'],
                          where(df['pm1'] >  1.05*pc,df['pm1']+2*(df['pm1']-1.05*pc),0)))

    df["pf2"]=where(df['pm2'] <  0.85*pc,pc,
                    where((df['pm2'] >= 0.85*pc) & (df['pm2'] <= 1.05*pc),df['pm2'],
                          where(df['pm2'] >  1.05*pc,df['pm2']+2*(df['pm2']-1.05*pc),0)))

    df["pf3"]=where(df['pm3'] <  0.85*pc,pc,
                    where((df['pm3'] >= 0.85*pc) & (df['pm3'] <= 1.05*pc),df['pm3'],
                          where(df['pm3'] >  1.05*pc,df['pm3']+2*(df['pm3']-1.05*pc),0)))
    dfa = df[["pf1","pf2","pf3"]].cumsum(axis = 0).iloc[[-1]]
    dfa["total"]=dfa.pf1+dfa.pf2+dfa.pf3
    y=dfa["total"].iloc[[-1]].iloc[0]
    yy.append(y)
    xx.append(x)
# yy
dx=pd.DataFrame()
dx["Potencia_contratada"]=xx
dx["Coste_anual"]=yy

minimo = dx['Coste_anual'].min()
indice = dx['Coste_anual'].idxmin()
poptima=dx.loc[indice,"Potencia_contratada"]



maximo = dx['Coste_anual'].max()
indice = dx['Coste_anual'].idxmax()
pmax=dx.loc[indice,"Potencia_contratada"]
ahorro=maximo-minimo

tt='Optimización de potencia contratada'
f, ax = plt.subplots(1)
f.set_figheight(5)
f.set_figwidth(15)
ax = plt.plot(xx,yy)
ax = plt.suptitle(tt)
ax = plt.ylabel("Euros")
ax = plt.xlabel("kw")
img = BytesIO()
plt.savefig(img, format='png')
img.seek(0)
plot_url = base64.b64encode(img.getvalue()).decode()
coste_g = ('<img src="data:image/png;base64,{}">'.format(plot_url))
plt.close()

In [ ]:
df[["pf1","pf2","pf3"]]
maximo

In [ ]:
139*3*12

# Análisis de los costes energéticos eléctricos
## Análisis por conceptos facturados.
El primer  paso para poder analizar los costes eléctricos es saber que componentes  tienes en una factura eléctrica y tendremos que dividir el coste de las  facturas del edificio auditado en todos estos conceptos. 

- Término de potencia (€/kW) es el abono de los derechos de uso de la infraestructura necesaria para tener la potencia contratada. El 100% son costes regulados. Se paga por kW contratado, lo utilices o no.
- Término de energía (€/kWh) es el precio que el consumidor paga por la energía que consume. Una parte son peajes de acceso y son regulados.
- Recargo por exceso de potencia: si sobrepasamos por encima del 105% de la potencia contratada tendremos un recargo.
- Recargo por energía reactiva:si la energía reactiva sobrepasa el 33% de la energía activa tendremos un recargo.
- Impuesto eléctrico:impuesto de 5,1127% sobre el total del coste de la factura.
- Alquiler de equipos de medida:coste de alquilar el equipo de medida y así evitar la inversión de comprarlo.
- IVA

{{dcem_g}}


{{dfa_g}}





## Optimizar potencia contratada.
Para el cálculo del término de potencia en los contratos 3.X, se mira la potencia máxima que se ha registrado para cada uno de los tres periodos del mes de facturación. Una vez tenemos  la potencia máxima registrada se aplican los siguiente supuestos para  cada una:

$$
  P_{medida} <  0.85\ P_{contratada} \Rightarrow P_{facturada}=P_{contratada}
$$

$$
0.85\ P_{contratada} \leq P_{medida} \leq 1.05\ P_{contratada}\Rightarrow P_{facturada}=P_{medida}
$$

$$
1.05\ P_{contratada} < P_{medida} \Rightarrow P_{facturada}=P_{medida} + 2(P_{medida}-1.05\ P_{contratada})
$$

Graficamente, iterando para distintos valores posibles de Potencia a contratar, se tiene.

{{coste_g}}
#### Datos observados:

- La funcion de coste tiene el minima en {{minimo}} Euros que corresponde a la potencia óptima de contratación de {{poptima}} kW lo que le supondir aun ahorro anual de {{ahorro}} Euros

In [ ]:
%%html
<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value=" 
Curso:  Auditorías energéticas
Alumno: Francisco Manuel Roman Gamez

"></form>